### ISSUE TITLE
uninstall targets installations CRD instead of installations.orchestrator.aiops.ibm.com

### ISSUE THREAD

**Issue by doormat18** [IBM/cp4waiops-samples#11]
The main uninstall script uses the `installation` CRD to find the AIOps instance, when in actuality the CRD is `installations.orchestrator.aiops.ibm.com`. At least this is the case on a ROKS install. The uninstall script fails b/c there are no installations.

**Comment by gyliu513** [comment]
Thanks @doormat18 , you are right, the short name for this CR is `install` but not `installation`.

```yaml
names:
    kind: Installation
    listKind: InstallationList
    plural: installations
    shortNames:
    - install
    singular: installation
```

@aadeshpa can you create a PR to fix this? Thanks!
